// This file is generated by GoAdmin CLI adm.
package tables

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "comments" => http://localhost:9033/admin/info/comments
// "users" => http://localhost:9033/admin/info/users
// "video_sources" => http://localhost:9033/admin/info/video_sources
// "videos" => http://localhost:9033/admin/info/videos
//
// example end
var Generators = map[string]table.Generator{

	"comments":      GetCommentsTable,
	"users":         GetUsersTable,
	"video_sources": GetVideosourcesTable,
	"videos":        GetVideosTable,

	// generators end
}
