# configs/config.yaml
server:
  port: ":8000" # API 服务的监听端口

mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "your_strong_password" # <-- 换成你自己的密码
  database: "video_platform_mvp"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

jwt:
  secret: "your-very-secret-key-change-it" # 换成一个更复杂的密钥
  expire_hours: 72 # Token 有效期（小时）

minio:
  endpoint: "127.0.0.1:9000"
  access_key_id: "minioadmin" # 这是 docker-compose.yml 中定义的
  secret_access_key: "minioadmin" # 这也是 docker-compose.yml 中定义的
  use_ssl: false # 本地开发，不使用 HTTPS
  bucket_name: "videos" # 我们将要把视频存放到这个桶里

rabbitmq:
  url: "amqp://user:password@127.0.0.1:5672/" # 这是 docker-compose 中定义的用户和密码
  transcode_queue: "video_transcoding_queue" # 我们给转码任务队列起个名字

ffmpeg:
  profiles:
    - name: "360p"
      resolution: "-2:360"
    - name: "720p"
      resolution: "-2:720"
    - name: "1080p"
      resolution: "-2:1080"